version: '3.8'
services:
  playwright:
    container_name: playwright-container
    # build:
    #   context: .
    #   dockerfile: dev.dockerfile
    image: mcr.microsoft.com/playwright:focal
    tty: true
    volumes:
      - ../:/usr/src/playwright
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    # ipc: host
    # network_mode: "host"
