name: E2E Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Install Playwright browsers
        run: |
          cd playwright
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd playwright
          npx playwright test --reporter=dot

      - name: Upload Playwright report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright/playwright-report/
